language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"

before_script:
  - chmod 777 Tests/tmp

  # Install p7zip
#  - sudo apt-get install p7zip-full
  - curl -L  http://downloads.sourceforge.net/project/p7zip/p7zip/15.09/p7zip_15.09_src_all.tar.bz2 > p7zip_15.09_src_all.tar.bz2
  - tar xjvf p7zip_15.09_src_all.tar.bz2
  - cd p7zip_15.09
  - make all3
  - sudo ./install.sh
  - sudo ln /usr/local/bin/7za /usr/bin/7za
  - cd ..

  - composer self-update && composer install --dev --prefer-source --no-interaction

script: phpunit --configuration phpunit.xml

notifications:
  email: false